language: rust
rust:
  - 1.12.0
  - stable
  - nightly

# Using 16MB stacks for deep test/debug recursion
env:
  global:
    - RUST_MIN_STACK=16777216

matrix:
  include:
  - rust: nightly
    env: FEATURES=unstable

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - |
    if [ $TRAVIS_RUST_VERSION != 1.12.0 ]; then
      which rustfmt || cargo install rustfmt
    fi

script:
  - |
    if [ $TRAVIS_RUST_VERSION != 1.12.0 ]; then
      cargo fmt --all -- --write-mode=diff
    fi
  - cargo build --features="$FEATURES"
  - |
    if [ $TRAVIS_RUST_VERSION == nightly ]; then
      cargo test --features="$FEATURES" &&
      cargo test --features="$FEATURES" -p rayon-core &&
      cargo test --features="$FEATURES" -p rayon-demo &&
      ./ci/highlander.sh
    fi
